apiVersion: v1
kind: ReplicationController
metadata: 
  name: hello-v1
spec:
  selector:
    app: hello
    version: v1
  template:
    metadata:
      labels:
        app: hello
        version: v1
    spec:
      containers:
      - name: hello
        image: 192.168.212.19/vitesss/hello:1750
        ports:
        - containerPort: 80
          protocol: TCP
