apiVersion: v1
kind: ReplicationController
metadata: 
  name: hello-v2
spec:
  selector:
    app: hello
    version: v2
  template:
    metadata:
      labels:
        app: hello
        version: v2
    spec:
      containers:
      - name: hello
        image: 192.168.212.19/vitesss/hello:1807
        ports:
        - containerPort: 80
          protocol: TCP
